# SQL Training — SuperMart E-Commerce Database

-- **Database file:** `supermart_sql_training.sql`


/* **Tables**
- `customers` (customer_id, customer_name, city, state, signup_date)
- `employees` (employee_id, employee_name, department, hire_date, manager_id)
- `products` (product_id, product_name, category, price, stock_qty)
- `orders` (order_id, customer_id, employee_id, order_date, status, region)
- `order_items` (order_item_id, order_id, product_id, quantity, unit_price, discount_pct)


--- */

## Part A — Easy to Moderate (fundamentals)
-- 1. **SELECT / FROM** — Retrieve all columns for every customer in the `customers` table.
     SELECT * 
     FROM customers;
     

-- 2. **WHERE** — List all products that belong to the `Electronics` category.
select *
from products
where category = 'Electronics';

-- 3. **WHERE (comparison)** — Find all products priced above ₹2000.
select *
from products
where price > 2000;

-- 4. **WHERE (multiple conditions)** — Find all orders with `status = 'Delivered'` AND `region = 'West'`.
select * from orders
where status = 'Delivered' and region = 'West';

-- 5. **DISTINCT** — List all unique categories present in the `products` table.

select distinct category
from products;

-- 6. **DISTINCT** — List all unique states customers come from.
select distinct state
from customers ;

-- 7. **ORDER BY** — List all products sorted by price, highest to lowest.
select *
from products
order by price desc;

-- 8. **LIKE / wildcard** — Find all customers whose name starts with `'A'`.
select * 
from customers
where customer_name like 'A%';

-- 9. **BETWEEN / IN** — Find all orders placed in the `region` `'North'` or `'South'` using `IN`.
select *
from orders
where region in ('north','south');

-- 10. **Aggregate basics** — Count the total number of orders in the `orders` table.
select count(order_id) as total_order
from orders;

-- 11. **GROUP BY** — For each `category`, find the average product price.
select category, avg(price) as avg_product_price
from products
group by category;

-- 12. **GROUP BY + ORDER BY** — For each `region`, count how many orders were placed, sorted from most to fewest.
select region, count(status) as order_placed
from orders
group by region
order by order_placed desc;

-- 13. **HAVING** — Find categories that have more than 4 products listed.
select category, count(product_name) as product_listed
from products
group by category
having product_listed > 4;

-- 14. **HAVING** — Find regions where the total number of orders is greater than 10.
select region, count(order_id) as total_orders
from orders
group by region
having count(order_id) > 10;
---

## Part B — Moderate to Hard (joins, subqueries, window functions, CTEs, views)

-- 15. **INNER JOIN** — List each order's `order_id`, `order_date`, and the `customer_name` who placed it.
select order_id, order_date, customer_name
from orders o
inner join customers c
on o.customer_id = c.customer_id;

-- 16. **INNER JOIN (3 tables)** — List `order_id`, `customer_name`, `product_name`, and `quantity` by joining `orders`, `order_items`, and `products`.
select order_id, customer_name, product_name, quantity
from orders
inner join customers
using (customer_id)
inner join order_items
using (order_id)
inner join products
using (product_id);

-- 17. **LEFT JOIN** — List every customer along with their orders — including customers who have never placed an order (should show NULLs for order columns).
 select c.customer_name, o.order_id
 from customers c
 left join orders o
 on c.customer_id = o.customer_id;
 
 -- 18. **JOIN + GROUP BY** — Find total revenue (`quantity * unit_price * (1 - discount_pct/100.0)`) generated by each `product_name`, sorted highest to lowest.
      select product_name, sum(quantity*unit_price * (1 - discount_pct/100.0)) as total_revenue
	from order_items ot
     join products p
    using(product_id)
    group by product_name 
    order by total_revenue desc;

-- 19. **JOIN + GROUP BY + HAVING** — Find customers who have placed more than 3 orders, showing `customer_name` and their order count.
select  customer_name , count(*) as total_order_count
from customers
join orders
using(customer_id) 
group by customer_name
having count(*) >3;

-- 20. **Self-JOIN** — Using the `employees` table, list each employee's name alongside their manager's name (`manager_id` refers back to `employee_id`).
select e.employee_name as employee,  m.employee_name as manager
from employees e
inner join employees m
on m.employee_id = e.manager_id;


-- 21. **Subquery (WHERE)** — Find all products priced above the average price of all products (use a subquery, not a hardcoded number).
select *
from products
where price >  (
select round(avg(price),0) from products);

-- 22. **Subquery (IN)** — Find all customers who have never placed an order (subquery on `orders`, without using LEFT JOIN this time).
select *
from customers
where customer_id  not in ( 
select customer_id
from orders);  

-- 23. **Window function — RANK/DENSE_RANK** — Rank products within each `category` by `price`, highest first (`PARTITION BY category ORDER BY price DESC`).
select category, product_id, price,
rank() over(partition by category order by price desc) as price_rank
from products;

-- 24. **Window function — ROW_NUMBER** — For each customer, number their orders from earliest to latest by `order_date`.
select customer_id, order_id, order_date,
       row_number() over (partition by customer_id order by order_date asc) as order_seq
from orders;

-- 25. **Window function — SUM OVER (running total)** — Calculate a running total of revenue by `order_date` across the whole `orders`/`order_items` data.
select o.order_date,
       sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct/100.0)) as daily_revenue,
       sum(sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct/100.0)))
           over (order by o.order_date asc) as running_total
from orders o
join order_items oi on o.order_id = oi.order_id
group by o.order_date
order by o.order_date;

-- 26. **CTE (WITH clause)** — Write a CTE that first computes total revenue per order, then use it in an outer query to find the top 5 highest-value orders.
with order_revenue as (
    select o.order_id,
           sum(oi.quantity * oi.unit_price * (1 - oi.discount_pct/100.0)) as revenue
    from orders o
    join order_items oi on o.order_id = oi.order_id
    group by o.order_id
)
select *
from order_revenue
order by revenue desc
limit 5;

-- 27. **CTE + JOIN** — Write a CTE that computes each employee's total number of orders handled, then join it back to `employees` to show `employee_name`, `department`, and `order_count`.
with emp_orders as (
    select employee_id, count(*) as order_count
    from orders
    group by employee_id
)
select e.employee_name, e.department, eo.order_count
from employees e
join emp_orders eo on e.employee_id = eo.employee_id;

-- 28. **VIEW** — Create a view called `vw_order_revenue` that shows `order_id`, `customer_name`, and total revenue for that order. Then query the view to find orders above ₹5000.

create or replace view vw_order_revenue as
select order_id, customer_name, sum(quantity*unit_price*(1- discount_pct/100.0)) as total_revenue
from orders o
join customers c
on o.customer_id = c.customer_id
join order_items
using (order_id) 
group by order_id, customer_name;

select * from vw_order_revenue 
where total_revenue > 5000;


-- 29. **Combined challenge** — Using a CTE + window function + JOIN, find the top-selling product (by total revenue) in *each* region.
with product_region_revenue as (
select region, product_name, sum(quantity*unit_price*(1-discount_pct/100.0)) as revenue
from orders
 join order_items 
using (order_id)
join products
using (product_id)
group by region, product_name ),
ranked as (
    select *,
           rank() over (partition by region order by revenue desc) as rnk
    from product_region_revenue
)
select region, product_name, revenue
from ranked
where rnk = 1;

### 

